export enum Status {
    PENDENTE = 'PENDENTE',
    EM_ANDAMENTO = 'EM_ANDAMENTO',
    CONVERTIDO = 'CONVERTIDO',
    ENVIADO = 'ENVIADO',
    EM_NEGOCIACAO = 'EM_NEGOCIACAO',
    FATURADO = 'FATURADO',
    A_FATURAR = 'A_FATURAR',
    CANCELADO = 'CANCELADO'
}